### ISSUE TITLE
java/lang/NoClassDefFoundError: java/lang/Object

### ISSUE THREAD

**Issue by Valbou** [salocinski/MyPass#1]
Bonjour,

Le logiciel ne se lance pas et affiche dans la console power shell : 
```
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
```

Je suis sous Win 10 avec JRE 8.

Merci.

**Comment by Valbou** [comment]
https://stackoverflow.com/questions/11808829/jre-1-7-returns-java-lang-noclassdeffounderror-java-lang-object

**Comment by salocinski** [comment]
Problème rencontre lorsque le JRE a connu une erreur dans son installation.
